"""任务分布统计 dashboard —— 数据集"成分表"。

两个出口：
- ``task_distribution``：纯数据（JSON），喂给检索 API 的 /episodes/stats
- ``render_html_report``：单文件 HTML 报告（无外部依赖，可直接发群/归档）

Grafana 看的是系统吞吐，这里看的是**数据本身**：任务配比、本体配比、
成功率、时长分布 —— 训练前先看成分。
"""

from __future__ import annotations

import html
import json
from collections import Counter
from typing import Any, Dict, Optional

import numpy as np
import pyarrow as pa


def task_distribution(meta: pa.Table) -> Dict[str, Any]:
    """episodes 元数据表 → 分布统计。"""
    if meta.num_rows == 0:
        return {"total_episodes": 0}

    def _counts(col: str) -> Dict[str, int]:
        vals = meta.column(col).to_pylist()
        return dict(Counter(str(v) for v in vals))

    durations = np.asarray(meta.column("duration").to_pylist(), dtype=np.float64)
    frames = np.asarray(meta.column("num_frames").to_pylist(), dtype=np.float64)
    success_vals = meta.column("success").to_pylist()
    succ = sum(1 for v in success_vals if v is True)
    fail = sum(1 for v in success_vals if v is False)
    unknown = len(success_vals) - succ - fail

    return {
        "total_episodes": meta.num_rows,
        "total_frames": int(frames.sum()),
        "by_task": _counts("task"),
        "by_embodiment": _counts("embodiment_tag"),
        "by_source": _counts("source"),
        "by_dataset": _counts("dataset_name"),
        "success": {
            "true": succ,
            "false": fail,
            "unlabeled": unknown,
            "rate_labeled": round(succ / max(succ + fail, 1), 4),
        },
        "duration_s": {
            "mean": round(float(durations.mean()), 2),
            "p50": round(float(np.percentile(durations, 50)), 2),
            "p95": round(float(np.percentile(durations, 95)), 2),
            "max": round(float(durations.max()), 2),
        },
        "frames": {
            "mean": round(float(frames.mean()), 1),
            "min": int(frames.min()),
            "max": int(frames.max()),
        },
    }


def _bar_rows(counts: Dict[str, int], max_width: int = 40) -> str:
    if not counts:
        return ""
    top = sorted(counts.items(), key=lambda kv: -kv[1])[:20]
    peak = max(v for _, v in top)
    rows = []
    for k, v in top:
        w = max(1, int(v / peak * max_width))
        rows.append(
            f"<tr><td class='k'>{html.escape(k)}</td>"
            f"<td><div class='bar' style='width:{w*8}px'></div></td>"
            f"<td class='v'>{v}</td></tr>"
        )
    return "\n".join(rows)


def render_html_report(
    stats: Dict[str, Any],
    out_path: str,
    title: str = "RobotLoop 数据质检报告",
    extra_sections: Optional[Dict[str, Any]] = None,
) -> str:
    """把统计结果渲染成单文件 HTML 报告，返回文件路径。"""

    def section(name: str, counts: Dict[str, int]) -> str:
        return f"<h2>{html.escape(name)}</h2><table>{_bar_rows(counts)}</table>"

    succ = stats.get("success", {})
    body = f"""
<h1>{html.escape(title)}</h1>
<div class="cards">
  <div class="card"><div class="num">{stats.get('total_episodes', 0)}</div><div>Episodes</div></div>
  <div class="card"><div class="num">{stats.get('total_frames', 0)}</div><div>Frames</div></div>
  <div class="card"><div class="num">{succ.get('rate_labeled', 0)*100:.0f}%</div><div>成功率（已标注）</div></div>
  <div class="card"><div class="num">{stats.get('duration_s', {}).get('mean', 0)}s</div><div>平均时长</div></div>
</div>
{section('任务分布', stats.get('by_task', {}))}
{section('本体分布', stats.get('by_embodiment', {}))}
{section('来源分布（teleop/sim/real）', stats.get('by_source', {}))}
{section('数据集分布', stats.get('by_dataset', {}))}
<h2>成功标记</h2>
<table>
<tr><td class='k'>成功</td><td class='v'>{succ.get('true', 0)}</td></tr>
<tr><td class='k'>失败</td><td class='v'>{succ.get('false', 0)}</td></tr>
<tr><td class='k'>未标注</td><td class='v'>{succ.get('unlabeled', 0)}</td></tr>
</table>
"""
    for name, payload in (extra_sections or {}).items():
        body += f"<h2>{html.escape(name)}</h2><pre>{html.escape(json.dumps(payload, ensure_ascii=False, indent=2))}</pre>"

    page = f"""<!DOCTYPE html>
<html lang="zh"><head><meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>
body {{ font-family: -apple-system, "PingFang SC", sans-serif; margin: 40px; color: #222; }}
h1 {{ font-size: 22px; }} h2 {{ font-size: 16px; margin-top: 28px; }}
table {{ border-collapse: collapse; }} td {{ padding: 3px 10px; font-size: 13px; }}
.k {{ color: #555; }} .v {{ font-variant-numeric: tabular-nums; }}
.bar {{ height: 14px; background: #4f7cff; border-radius: 2px; }}
.cards {{ display: flex; gap: 16px; margin: 18px 0; }}
.card {{ border: 1px solid #e5e5e5; border-radius: 8px; padding: 14px 22px; text-align: center; }}
.num {{ font-size: 26px; font-weight: 600; color: #4f7cff; }}
pre {{ background: #f7f7f8; padding: 12px; border-radius: 6px; font-size: 12px; }}
</style></head><body>{body}
<footer><small>generated by robotloop.quality.dashboard</small></footer>
</body></html>"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(page)
    return out_path
